### PR TITLE
Stop development assets shipping in jar

### PR DESCRIPTION
**Pull request by lorddoig**
It was duplicating everything in `cljs.core` in my autocompletion.

### CODE REVIEW

**Comment by noprompt** [comment]
Thanks for fixing this. This is a mistake I have to stop making. I'd like to merge this but could you undo the formatting changes to `project.clj` file? I'm not a huge fan of aligning the key/value pairs. Thanks!

**Comment by lorddoig** [comment]
Better?

**Comment by noprompt** [comment]
@lorddoig Yes. Thank you. There are a few things I'm not familiar with here but I can read about those on my own. Thanks again for the patch.

**Comment by lorddoig** [comment]
@noprompt No problem! Happy to help.

**Pull request merged**
